///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace OBS_Studio_Desktop_App
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the OBS_Studio_Desktop_AppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e331a061-ea27-48fb-9fe5-14b9867b2ad5")]
    public partial class OBS_Studio_Desktop_AppRepository : RepoGenBaseFolder
    {
        static OBS_Studio_Desktop_AppRepository instance = new OBS_Studio_Desktop_AppRepository();

        /// <summary>
        /// Gets the singleton class instance representing the OBS_Studio_Desktop_AppRepository element repository.
        /// </summary>
        [RepositoryFolder("e331a061-ea27-48fb-9fe5-14b9867b2ad5")]
        public static OBS_Studio_Desktop_AppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public OBS_Studio_Desktop_AppRepository() 
            : base("OBS_Studio_Desktop_AppRepository", "/", null, 0, false, "e331a061-ea27-48fb-9fe5-14b9867b2ad5", ".\\RepositoryImages\\OBS_Studio_Desktop_AppRepositorye331a061.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e331a061-ea27-48fb-9fe5-14b9867b2ad5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class OBS_Studio_Desktop_AppRepositoryFolders
    {
    }
#pragma warning restore 0436
}
